export const RULE_KEYS = [
  'game.player_count',
  'game.factions',
  'game.role_setup',
  'game.authority',
  'game.first_night_number',
  'game.first_day_number',
  'game.round_increment',
  'flow.lifecycle',
  'flow.night_stages',
  'flow.guard_seer_parallel',
  'flow.wait_guard_seer',
  'flow.wait_wolf_kill',
  'flow.atomic_night_resolution',
  'flow.day_stages',
  'flow.stage_revision_required',
  'flow.command_id_required',
  'flow.timeout_policy',
  'roles.werewolf.alignment',
  'roles.werewolf.knows_teammates',
  'roles.werewolf.can_self_kill',
  'roles.werewolf.can_empty_kill',
  'roles.werewolf.kill_target',
  'roles.werewolf.kill_decision',
  'roles.werewolf.kill_tie',
  'roles.seer.alignment',
  'roles.seer.checks_per_night',
  'roles.seer.check_self',
  'roles.seer.result_granularity',
  'roles.seer.result_visibility',
  'roles.guardian.alignment',
  'roles.guardian.guards_per_night',
  'roles.guardian.can_guard_self',
  'roles.guardian.consecutive_same_target',
  'roles.guardian.blocks_wolf_kill',
  'roles.guardian.action_visibility',
  'roles.witch.alignment',
  'roles.witch.antidote_count',
  'roles.witch.poison_count',
  'roles.witch.antidote_target_binding',
  'roles.witch.guarded_target_notice',
  'roles.witch.antidote_when_no_notice',
  'roles.witch.poison_target',
  'roles.witch.can_self_save',
  'roles.witch.can_use_both_potions_same_night',
  'roles.witch.poison_ignores_guard',
  'roles.witch.action_visibility',
  'roles.hunter.alignment',
  'roles.hunter.shoot_trigger',
  'roles.hunter.shoot_when_poisoned',
  'roles.hunter.shoot_when_wolf_killed',
  'roles.hunter.shot_target',
  'roles.hunter.may_skip_shot',
  'roles.villager.alignment',
  'roles.villager.night_ability',
  'resolution.same_guard_same_save',
  'resolution.peaceful_night_public_result',
  'resolution.wolves_know_save_cause',
  'resolution.public_death_causes',
  'resolution.simultaneous_deaths',
  'resolution.dead_players_cannot_act',
  'victory.mode',
  'victory.good_win',
  'victory.werewolf_win_gods',
  'victory.werewolf_win_villagers',
  'victory.check_points',
  'victory.simultaneous_both_sides_condition',
  'speech.public_day_speech',
  'speech.wolf_night_chat',
  'speech.spectator_can_speak',
  'speech.speech_order',
  'speech.last_words_scope',
  'speech.speech_limits',
  'speech.daily_summary_quota',
  'voting.eligible_voters',
  'voting.eligible_targets',
  'voting.abstain_allowed',
  'voting.vote_visibility_before_lock',
  'voting.result_visibility',
  'voting.tie_policy',
  'voting.repeat_vote_scope',
  'voting.exile_effect',
  'visibility.classes',
  'visibility.assign_at_event_creation',
  'visibility.public_forbidden_fields',
  'visibility.omniscient_sees_game_facts',
  'visibility.omniscient_sees_secrets',
  'validation.role_alive_stage',
  'validation.target_validation',
  'validation.duplicate_command',
  'validation.stale_revision',
  'validation.expired_command',
  'validation.invalid_ruleset',
] as const;

export type RuleKey = (typeof RULE_KEYS)[number];

export const RULE_TEXT_KEYS = [
  'rule.flow.night_order',
  'rule.werewolf.self_kill',
  'rule.victory.edge_elimination',
  'rule.guardian.witch_notice_blocked',
  'rule.werewolf.peaceful_night_unknown_cause',
  'rule.hunter.exile_only',
  'rule.guardian.no_consecutive_target',
  'rule.witch.antidote_server_bound',
  'rule.seer.alignment_only',
  'rule.visibility.four_classes',
  'rule.voting.pending_tie_policy',
  'rule.witch.pending_self_save',
] as const;

export type RuleTextKey = (typeof RULE_TEXT_KEYS)[number];

export const RULE_VALUES = {
  'game.player_count': 12,
  'game.factions': ['wolf', 'good'],
  'game.role_setup': { wolf: 4, seer: 1, witch: 1, hunter: 1, guardian: 1, villager: 4 },
  'game.authority': 'server',
  'game.first_night_number': 1,
  'game.first_day_number': 1,
  'game.round_increment': 'before_next_night',
  'flow.lifecycle': ['lobby', 'role_confirm', 'night', 'day', 'ended'],
  'flow.night_stages': ['guard_seer', 'wolf_discussion', 'wolf_vote', 'witch', 'resolve'],
  'flow.guard_seer_parallel': true,
  'flow.wait_guard_seer': 'both_complete_or_timeout',
  'flow.wait_wolf_kill': 'kill_locked',
  'flow.atomic_night_resolution': true,
  'flow.day_stages': ['dawn', 'speech', 'discussion', 'voting', 'exile_result', 'last_words', 'hunter', 'day_end'],
  'flow.stage_revision_required': true,
  'flow.command_id_required': true,
  'flow.timeout_policy': 'deterministic_auto_action',
  'roles.werewolf.alignment': 'wolf',
  'roles.werewolf.knows_teammates': true,
  'roles.werewolf.can_self_kill': true,
  'roles.werewolf.can_empty_kill': true,
  'roles.werewolf.kill_target': 'any_alive_player',
  'roles.werewolf.kill_decision': 'team_vote',
  'roles.werewolf.kill_tie': '平票随机杀一个',
  'roles.seer.alignment': 'good',
  'roles.seer.checks_per_night': 1,
  'roles.seer.check_self': false,
  'roles.seer.result_granularity': 'alignment_only',
  'roles.seer.result_visibility': 'role_private',
  'roles.guardian.alignment': 'good',
  'roles.guardian.guards_per_night': 1,
  'roles.guardian.can_guard_self': true,
  'roles.guardian.consecutive_same_target': false,
  'roles.guardian.blocks_wolf_kill': true,
  'roles.guardian.action_visibility': 'role_private',
  'roles.witch.alignment': 'good',
  'roles.witch.antidote_count': 1,
  'roles.witch.poison_count': 1,
  'roles.witch.antidote_target_binding': 'current_locked_kill_target',
  'roles.witch.guarded_target_notice': 'no_kill_notice',
  'roles.witch.antidote_when_no_notice': false,
  'roles.witch.poison_target': 'any_other_alive_player',
  'roles.witch.can_self_save': true,
  'roles.witch.can_use_both_potions_same_night': false,
  'roles.witch.poison_ignores_guard': true,
  'roles.witch.action_visibility': 'role_private',
  'roles.hunter.alignment': 'good',
  'roles.hunter.shoot_trigger': 'exile_only',
  'roles.hunter.shoot_when_poisoned': false,
  'roles.hunter.shoot_when_wolf_killed': false,
  'roles.hunter.shot_target': 'any_other_alive_player',
  'roles.hunter.may_skip_shot': true,
  'roles.villager.alignment': 'good',
  'roles.villager.night_ability': 'none',
  'resolution.same_guard_same_save': 'guard_prevents_notice_and_antidote',
  'resolution.peaceful_night_public_result': 'peaceful_night_only',
  'resolution.wolves_know_save_cause': false,
  'resolution.public_death_causes': false,
  'resolution.simultaneous_deaths': 'apply_all_then_check_win',
  'resolution.dead_players_cannot_act': true,
  'victory.mode': 'edge_elimination',
  'victory.good_win': 'all_werewolves_dead',
  'victory.werewolf_win_gods': 'all_good_special_roles_dead',
  'victory.werewolf_win_villagers': 'all_villagers_dead',
  'victory.check_points': 'after_atomic_resolution',
  'victory.simultaneous_both_sides_condition': 'draw',
  'speech.public_day_speech': 'all_alive_players',
  'speech.wolf_night_chat': 'alive_werewolves_private',
  'speech.spectator_can_speak': false,
  'speech.speech_order': 'random_clockwise_or_counterclockwise',
  'speech.last_words_scope': 'exile_only_two_rounds',
  'speech.speech_limits': {
    round_speech_chars: 100,
    free_discussion_chars: 150,
    last_words_chars: 80,
    vote_reason_chars: 40,
    daily_summary_chars: 300,
  },
  'speech.daily_summary_quota': 1,
  'voting.eligible_voters': 'all_alive_players',
  'voting.eligible_targets': 'other_alive_players',
  'voting.abstain_allowed': true,
  'voting.vote_visibility_before_lock': 'hidden',
  'voting.result_visibility': 'public_after_lock',
  'voting.tie_policy': 'single_revote_then_no_exile',
  'voting.repeat_vote_scope': 'tied_candidates_only_candidates_cannot_vote_no_abstain_max_once',
  'voting.exile_effect': 'target_dies',
  'visibility.classes': ['public', 'role_private', 'wolf_private', 'spectator_omniscient'],
  'visibility.assign_at_event_creation': true,
  'visibility.public_forbidden_fields': [
    'hidden_roles',
    'guard_target',
    'seer_target',
    'seer_result',
    'wolf_chat',
    'wolf_votes',
    'kill_target',
    'witch_notice',
    'potion_action',
    'action_completion_side_channel',
    'full_prompt',
    'api_key',
  ],
  'visibility.omniscient_sees_game_facts': true,
  'visibility.omniscient_sees_secrets': false,
  'validation.role_alive_stage': 'required',
  'validation.target_validation': 'shared_for_human_and_ai',
  'validation.duplicate_command': 'reject_or_return_original_result',
  'validation.stale_revision': 'reject',
  'validation.expired_command': 'reject',
  'validation.invalid_ruleset': 'reject_before_game',
} as const satisfies Record<RuleKey, unknown>;

export const RULESET = {
  id: 'werewolf.v3.default-12p',
  schemaVersion: 1,
  rulesetVersion: '3.0.0-stage0-finalized',
  locale: 'zh-CN',
  values: RULE_VALUES,
} as const;

export function getRuleValue<K extends RuleKey>(key: K): (typeof RULE_VALUES)[K] {
  return RULE_VALUES[key];
}
